version: "2"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      PORT: "80"
      NODE_ENV: "production"
      dbURI: "mongodb://mongo:27017/pokerPlanning"
    hostname: poker
    links:
      - mongo
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
